apiVersion: v1
kind: Service
metadata:
  name: k8s-events-notifier
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    airspot.krules.dev/ruleset: k8s-events-notifier
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-events-notifier
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    matchLabels:
      airspot.krules.dev/ruleset: my-base-ruleset
  replicas: 1
  template:
    metadata:
      name: k8s-events-notifier
      labels:
        airspot.krules.dev/type: ruleset
        airspot.krules.dev/ruleset: k8s-events-notifier
    spec:
      serviceAccountName: lab-serviceaccount
      containers:
        - name: ruleset
          volumeMounts:
            - name: config-slack-web-hooks-volume
              mountPath: /krules/config/apps/slack
      volumes:
        - name: config-slack-web-hooks-volume
          configMap:
            name: config-slack-webhooks
      #- image: /use-case-tim-k8s-events-notifier:0.1.0
