apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-firewall-k8s-events
spec:
  broker: default
  filter:
    attributes:
        multusapp: firewall
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: k8s-events-notifier

---

apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:

  name: on-new-firewall-approved

spec:
  filter:
    attributes:

      type: new-firewall-approved

  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: k8s-events-notifier
