apiVersion: v1
kind: Service
metadata:
  name: network-configurator
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    airspot.krules.dev/ruleset: network-configurator
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-configurator
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    matchLabels:
      airspot.krules.dev/ruleset: network-configurator
  replicas: 1
  template:
    metadata:
      name: network-configurator
      labels:
        airspot.krules.dev/type: ruleset
        airspot.krules.dev/ruleset: network-configurator
    spec:
      serviceAccountName: lab-serviceaccount
      containers:
        - name: ruleset
