apiVersion: v1
kind: Service
metadata:
  name: multus-ifaces-annotator
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    airspot.krules.dev/ruleset: multus-ifaces-annotator
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-ifaces-annotator
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    matchLabels:
      airspot.krules.dev/ruleset: multus-ifaces-annotator
  replicas: 1
  template:
    metadata:
      name: multus-ifaces-annotator
      labels:
        airspot.krules.dev/type: ruleset
        airspot.krules.dev/ruleset: multus-ifaces-annotator
    spec:
      serviceAccountName: lab-serviceaccount
      containers:
        - name: ruleset
