apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: redis
 name: redis-master
spec:
 replicas: 1
 selector:
   matchLabels:
     app: redis
     role: master
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: redis
       role: master
   spec:
     containers:
     - image: k8s.gcr.io/redis:e2e
       imagePullPolicy: IfNotPresent
       name: master
       ports:
       - containerPort: 6379
         protocol: TCP
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
       volumeMounts:
         - name: redis
           mountPath: /data
     dnsPolicy: ClusterFirst
     restartPolicy: Always
     schedulerName: default-scheduler
     securityContext: {}
     terminationGracePeriodSeconds: 30
     volumes:
       - name: redis
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: redis
   role: master
 name: redis-master
spec:
 ports:
 - port: 6379
   protocol: TCP
   targetPort: 6379
 selector:
   app: redis
   role: master
 sessionAffinity: None
 type: ClusterIP
