apiVersion: sources.knative.dev/v1alpha2
kind: ApiServerSource
metadata:
  name: apiserversource
spec:
  serviceAccountName: lab-serviceaccount
  mode: Resource
  resources:
#    - apiVersion: v1
#      kind: ConfigMap
#    - apiVersion: genoplab.airspot.tech/v1alpha1
#      kind: NetConfig
    - apiVersion: v1
      kind: Pod
#    - apiVersion: v1
#      kind: Event
#    - apiVersion: serving.knative.dev/v1beta1
#      kind: Service
#    - apiVersion: v1
#      kind: Deployment
    - apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition


  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: k8s-subscriber
---
