apiVersion: v1
kind: Service
metadata:
  name: on-firewall-status-change
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    airspot.krules.dev/ruleset: on-firewall-status-change
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-firewall-status-change
  labels:
    airspot.krules.dev/type: ruleset
spec:
  selector:
    matchLabels:
      airspot.krules.dev/ruleset: on-firewall-status-change
  replicas: 1
  template:
    metadata:
      name: on-firewall-status-change
      labels:
        airspot.krules.dev/type: ruleset
        airspot.krules.dev/ruleset: on-firewall-status-change
    spec:
      serviceAccountName: lab-serviceaccount
      containers:
        - name: ruleset
